-- ─────────────────────────────────────────────────────────────
-- Migration 006 — Triage Queue
-- ─────────────────────────────────────────────────────────────
-- Adds a single source of truth for "something has changed with
-- this patient that a clinician should look at." Flags are
-- generated by the patient portal (self PHQ-9/GAD-7, safety-plan
-- triggers, chat keyword matches, silence) and consumed by the
-- clinic portal queue page.
--
-- Severity mirrors AfterWard's red/amber/green triage pattern.
-- ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS triage_flags (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  patient_id        UUID NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  therapist_id      UUID NOT NULL REFERENCES therapists(id) ON DELETE CASCADE,

  severity          TEXT NOT NULL CHECK (severity IN ('red','amber','green')),
  flag_type         TEXT NOT NULL,
    -- 'phq9_high' | 'phq9_severe' | 'phq9_q9_positive'
    -- 'gad7_high' | 'gad7_severe'
    -- 'safety_plan_warning' | 'safety_plan_created_self'
    -- 'chat_risk_keyword' | 'silence_7d' | 'mood_drop_sustained'
  trigger_source    TEXT NOT NULL
    CHECK (trigger_source IN ('outcome_scores','safety_plan','chat_session','journal','system','manual')),
  source_id         UUID,

  summary           TEXT NOT NULL,         -- one-liner for the queue row
  trigger_data      JSONB NOT NULL DEFAULT '{}'::jsonb,

  status            TEXT NOT NULL DEFAULT 'open'
    CHECK (status IN ('open','acknowledged','resolved')),
  acknowledged_at   TIMESTAMPTZ,
  acknowledged_by   UUID REFERENCES therapists(id),
  resolved_at       TIMESTAMPTZ,
  resolved_by       UUID REFERENCES therapists(id),
  resolution_note   TEXT,

  created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Fast queue query for one therapist, ordered by severity then time
CREATE INDEX IF NOT EXISTS triage_flags_therapist_open_idx
  ON triage_flags (therapist_id, status, severity, created_at DESC);

-- Fast lookup for patient detail page
CREATE INDEX IF NOT EXISTS triage_flags_patient_idx
  ON triage_flags (patient_id, created_at DESC);

ALTER TABLE triage_flags ENABLE ROW LEVEL SECURITY;

-- Therapist: full control over their own patients' flags
DROP POLICY IF EXISTS "therapist_manage_own_patient_flags" ON triage_flags;
CREATE POLICY "therapist_manage_own_patient_flags"
  ON triage_flags
  FOR ALL
  USING (
    therapist_id IN (
      SELECT id FROM therapists WHERE auth_user_id = auth.uid()
    )
  )
  WITH CHECK (
    therapist_id IN (
      SELECT id FROM therapists WHERE auth_user_id = auth.uid()
    )
  );

-- Patient: may read their own flags (they may see a "your therapist
-- has been notified" banner in the PWA). No write access — flags are
-- system-generated or clinician-managed.
DROP POLICY IF EXISTS "patient_read_own_flags" ON triage_flags;
CREATE POLICY "patient_read_own_flags"
  ON triage_flags
  FOR SELECT
  USING (
    patient_id IN (
      SELECT id FROM patients WHERE portal_auth_user_id = auth.uid()
    )
  );
